name: Zip and Upload Ingestion Script

on:
  push:
    branches:
      - '*'


jobs:
  zip_and_upload:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Authenticate to GCP
      run: |
        gcloud auth list

      - name: test
        run: echo 'test'

      # - name: Zip Cloud Function
      #   run: |
      #     # Replace with your actual build steps to create the Cloud Function
      #     # For example, if your function is in a folder named 'my-function':
      #     zip -r function.zip my-function

      # - name: Upload to GCS bucket
      #   uses: google-github-actions/upload-cloud-storage@v2
      #   with:
      #     path: function.zip
      #     destination: your-bucket-name

      # - name: Set output variable
      #   id: uploaded_files
      #   run: echo "::set-output name=uploaded::$GITHUB_WORKSPACE/function.zip"

      # - name: Use the uploaded file path
      #   run: echo "The file was uploaded to gs://your-bucket-name/function.zip"
