name: Zip and Upload Ingestion Script

on:
  push:
    branches:
      - '*'


jobs:
  zip_and_upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
            create_credentials_file: 'true'
            workload_identity_provider: 'projects/113330691559/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions'
            service_account: 'github-actions-267@the-scribe-429016.iam.gserviceaccount.com'
            token_format: "access_token"
            access_token_lifetime: "120s"

      # - name: checker
      #   run: |
      #     gcloud auth login
      #     gcloud auth application-default login
      #     gsutil ls

      # - name: zip function
      #   run: |
      #     cd engine
      #     zip engine.zip engine.py

      # - name: Upload to cloud
      #   run: gsutil cp engine.zip gs://ingestion-engine-code/engine.zip

      # - name: Deploy to Cloud Function
      #   run: gcloud functions deploy ingestion --source=gs://ingestion-engine-code/engine.zip 

      # - name: Zip Cloud Function
      #   run: |
      #     # Replace with your actual build steps to create the Cloud Function
      #     # For example, if your function is in a folder named 'my-function':
      #     zip -r function.zip my-function

      # - name: Upload to GCS bucket
      #   uses: google-github-actions/upload-cloud-storage@v2
      #   with:
      #     path: function.zip
      #     destination: your-bucket-name

      # - name: Set output variable
      #   id: uploaded_files
      #   run: echo "::set-output name=uploaded::$GITHUB_WORKSPACE/function.zip"

      # - name: Use the uploaded file path
      #   run: echo "The file was uploaded to gs://your-bucket-name/function.zip"
